# Generated by Django 6.0.3 on 2026-03-30 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('loan_request', 'Solicitacao de emprestimo'), ('loan_approved', 'Emprestimo aprovado'), ('loan_rejected', 'Emprestimo rejeitado'), ('return_reminder', 'Lembrete de devolucao'), ('return_overdue', 'Devolucao atrasada'), ('reservation', 'Nova reserva'), ('new_message', 'Nova mensagem'), ('review', 'Nova avaliacao'), ('system', 'Sistema')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacao',
                'verbose_name_plural': 'Notificacoes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
