# Generated by Django 6.0.3 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_deleted_at_notification_is_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                ],
                "ordering": ["-created_at"],
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("loan_request", "Solicitação de empréstimo"),
                    ("loan_approved", "Empréstimo aprovado"),
                    ("loan_rejected", "Empréstimo rejeitado"),
                    ("return_reminder", "Lembrete de devolução"),
                    ("return_overdue", "Devolução atrasada"),
                    ("reservation", "Nova reserva"),
                    ("new_message", "Nova mensagem"),
                    ("review", "Nova avaliação"),
                    ("system", "Sistema"),
                ],
                max_length=30,
            ),
        ),
    ]
