# Generated by Django 6.0.3 on 2026-03-30 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('in_progress', 'Em andamento'), ('returned', 'Devolvido'), ('overdue', 'Atrasado'), ('cancelled', 'Cancelado'), ('disputed', 'Em disputa')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_date', models.DateTimeField(help_text='Data/hora combinada para retirada')),
                ('expected_return_date', models.DateTimeField(blank=True, help_text='Data/hora prevista para devolucao', null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, help_text='Data/hora real da devolucao', null=True)),
                ('borrower_notes', models.TextField(blank=True)),
                ('lender_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(help_text='Usuario que pega emprestado', on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_borrower', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='items.item')),
                ('lender', models.ForeignKey(help_text='Usuario que empresta (dono do item)', on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_lender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('fulfilled', 'Realizada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('desired_date', models.DateTimeField(help_text='Data desejada para o emprestimo')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='items.item')),
                ('loan', models.ForeignKey(blank=True, help_text='Emprestimo vigente que originou esta reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='loans_loan_borrowe_d07c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['lender', 'status'], name='loans_loan_lender__d9e9d1_idx'),
        ),
    ]
