# Generated by Django 6.0.3 on 2026-06-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_loan_deleted_at_loan_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "indexes": [
                    models.Index(fields=["status"], name="loans_loan_status_962e99_idx"),
                    models.Index(
                        fields=["borrower", "status"],
                        name="loans_loan_borrowe_d07c9e_idx",
                    ),
                    models.Index(
                        fields=["lender", "status"],
                        name="loans_loan_lender__d9e9d1_idx",
                    ),
                ],
                "ordering": ["-requested_at"],
                "verbose_name": "Empréstimo",
                "verbose_name_plural": "Empréstimos",
            },
        ),
        migrations.AlterField(
            model_name="loan",
            name="actual_return_date",
            field=models.DateTimeField(
                blank=True, help_text="Data/hora real da devolução", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="borrower",
            field=models.ForeignKey(
                help_text="Usuário que pega emprestado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans_as_borrower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="expected_return_date",
            field=models.DateTimeField(
                blank=True, help_text="Data/hora prevista para devolução", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="lender",
            field=models.ForeignKey(
                help_text="Usuário que empresta (dono do item)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans_as_lender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="desired_date",
            field=models.DateTimeField(help_text="Data desejada para o empréstimo"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                help_text="Empréstimo vigente que originou esta reserva",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="loans.loan",
            ),
        ),
    ]
