# Generated by Django 6.0.3 on 2026-06-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_update_loan_labels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
