# Generated by Django 6.0.3 on 2026-05-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
