# Generated by Django 6.0.3 on 2026-06-12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_deleted_at_review_is_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "unique_together": {("loan", "reviewer")},
            },
        ),
        migrations.AlterField(
            model_name="review",
            name="user_rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                help_text="Nota para o usuário/fornecedor (1-5)"
            ),
        ),
    ]
