# Generated by Django 6.0.3 on 2026-03-30 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tool', 'Ferramenta'), ('service', 'Servico')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Nome do icone', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('segregation', models.CharField(choices=[('hobby', 'Hobby'), ('semi_professional', 'Semi Profissional'), ('professional', 'Profissional')], default='hobby', help_text='Nivel de uso/qualidade da ferramenta', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'Novo'), ('good', 'Bom estado'), ('used', 'Usado'), ('worn', 'Desgastado')], default='good', max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado informativo (nao eh venda - RF002)', max_digits=10, null=True)),
                ('availability', models.CharField(choices=[('available', 'Disponivel'), ('borrowed', 'Emprestado'), ('reserved', 'Reservado'), ('unavailable', 'Indisponivel')], default='available', max_length=20)),
                ('allow_reservation', models.BooleanField(default=True, help_text='Permite reserva antecipada (RF005)')),
                ('is_active', models.BooleanField(default=True)),
                ('times_borrowed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='items/')),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
            options={
                'verbose_name': 'Imagem do Item',
                'verbose_name_plural': 'Imagens dos Itens',
                'ordering': ['-is_cover', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='items.category')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.subcategory'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['availability', 'is_active'], name='items_item_availab_a1b838_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['subcategory'], name='items_item_subcate_d3bb57_idx'),
        ),
    ]
