# Generated by Django 6.0.3 on 2026-05-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
