# Generated by Django 6.0.3 on 2026-06-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_deleted_at_item_is_deleted"),
        ("items", "0002_itemimage_url_field"),
    ]

    operations = []
